# Generated by Django 4.1.7 on 2023-02-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fitnessplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
